import type { Metadata } from "next";
import "../globals.css";
import TopNavigation from "@/src/components/topNavigation";
import { ThemeProvider } from "@/src/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider defaultTheme="light" enableSystem disableTransitionOnChange>
      <TopNavigation />
      {children}
    </ThemeProvider>
  );
}
