import type { Metadata } from "next";
import "../globals.css";
import TopNavigation from "@/src/components/topNavigation";
import { ThemeProvider } from "@/src/theme-provider";
import Footer from "@/src/components/footer";
import { fetchAPI } from "./utils/fetch-api";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}>) {
  const { lang } = await params;

  const pageHeaders = await fetchAPI("/pages", { fields: ["heading"] });
  
  return (
    <ThemeProvider defaultTheme="light" enableSystem disableTransitionOnChange>
      <TopNavigation locale={lang} headers={pageHeaders} />
      {children}
      <Footer locale={lang} />
    </ThemeProvider>
  );
}
